// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ComponentsList: typeof import('./src/components/ComponentsList.vue')['default']
    EditorWrapper: typeof import('./src/components/EditorWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateList: typeof import('./src/components/TemplateList.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
